### ISSUE TITLE
Custom magic

### ISSUE THREAD

**Issue by james-grant1** [JDBetteridge/nbfancy#4]
Investigate resolution of local magic

**Comment by JDBetteridge** [comment]
This issue is a pain, currently this is resolved as part of `nbfancy configure`.

One caveat is that if nbfancy is installed in a venv, the edit to global config now affects global iPython. Unlike with Jupyter, where adding w3 CSS is fairly inoffensive to the user, custom magic can't be found and spews errors evey time global iPython is started :-(.

Current recommendation is that users install nbfancy with `--user` instead of venv if they want magics. Or install in a venv and avoid magics.

This is not ideal and perhaps it should be raised upstream?
