### ISSUE TITLE
nbfancy image

### ISSUE THREAD

**Issue by james-grant1** [JDBetteridge/nbfancy#9]
nbfancy has a (nb)fancy name, now it needs a (nb)fancy logo.

**Comment by JDBetteridge** [comment]
Do we know anyone who can help wit this?

**Comment by JDBetteridge** [comment]
<img alt="NBfancy" src="https://raw.githubusercontent.com/JDBetteridge/nbfancy/python_package/nbfancy/nbfancylogo.png" height="80">

What do you think?

**Comment by james-grant1** [comment]
It’s fancy … if easy to do, what does it look like if ‘ancy’ is not fancy?

**Comment by JDBetteridge** [comment]
Italic ![ALT2nbfancylogo](https://user-images.githubusercontent.com/43041811/56886635-50b92f00-6a67-11e9-8fb3-8afac122669c.png)

Or non italic? ![ALTnbfancylogo](https://user-images.githubusercontent.com/43041811/56886636-50b92f00-6a67-11e9-9fe6-164d17795e29.png)

Probably not essential that we decide right now, but I do bytestring encode the image in the header (because I can...)

**Comment by james-grant1** [comment]
I think I prefer non-italic, but the I am simple.  As you say it isn’t the most pressing thing right now.
